application:
  title: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    ROOT: ${LOG_LEVEL_APP:INFO}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/products}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:example}
    driverClassName: org.postgresql.Driver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        max.poll.interval.ms: 900000
        max.poll.records: 10

kafka:
  topics:
    commands:
      products: ${KAFKA_TOPICS_COMMANDS_PRODUCTS:products-command}
    events:
      products: ${KAFKA_TOPICS_EVENTS_PRODUCTS:products-event}
    dlt:
      products: ${KAFKA_TOPICS_DLT_VEHICLE_PRODUCTS:products-dlt}

security:
  api-key:
    enabled: ${SECURITY_API_KEY_ENABLED:true}
    value: ${SECURITY_API_KEY_VALUE:51a20734-39de-4965-93f9-8e14c7d9e91a}
